---
title: "projectmessi_md"
author: "rey"
date: "2024-05-15"
output: html_document
---

## Instalação de Pacotes

``` r
install.packages("tidyverse")     #instalando tidyverse
install.packages("readxl")        #install pra ler excel
install.packages("rmarkdown")     #instalando markdown   
library(dplyr)                    #library de analise
library(ggplot2)
library(tidyverse)
library(readxl)
library(lubridate)
```

## Importar os dados

-   realizar a importação dos dados para o RStudio

``` r
df <- read.csv("C:/Users/path/path/path/messi/messi.csv") #realiza a importação dos dados CSV para a variavel df
```

-   visualizar os dados

``` r
View(df)          #abre o df
str(df)           #mostra toda a estrutura do df
unique(df$Season) #mostra os valores unicos na coluna season  
```

### Tratamento de dados

-   tratando os dados de Season fora de padrao

``` r
select(df, Season)               #SELECT padrao para visualizar a Season
df$Season <- gsub("Dec-13", "13/14", df$Season) #padronizando dados
df$Season <- gsub("11-Dec", "11/12", df$Season) #padronizando dados
```

-   tratando os dados de Data fora de padrao

``` r
df$Date <- ifelse(nchar(df$Date) < 8, paste0("0", df$Date), df$Date) #adicionando 0 nos meses que nao tem no inicio do formato MDY
df$Date <- gsub("/", "-", df$Date)                #alterando os / por -
df$Date <- as.Date(df$Date, format = "%m-%d-%y")  # Converter para o formato de data do R
df$Date <- format(df$Date, "%Y-%m-%d")            # Converter de volta para uma string no formato YYYY-MM-DD

df$Date <- ymd(df$Date) # tipo chr para tipo Date
```

-   limpando os dados do Result tirando do formato x:xx, separando em duas colunas, sendo Home e Away

``` r
#separando Home e Away do resultado

# Separar os valores em duas colunas
df <- cbind(df, do.call(rbind, strsplit(as.character(df$Result), ":")))

# Renomear as colunas resultantes
colnames(df)[14:15] <- c("Home", "Away")

df$Away <- gsub("2 AET", "2", df$Away)#removendo 1 exceção
df$Away <- gsub("4 AET", "4", df$Away)#removendo 1 exceção
df$Away <- sub("^0", "", df$Away)     #removendo 0 a esquerda

df$Home <- as.numeric(as.character(df$Home))  #chr para int
df$Away <- as.numeric(as.character(df$Away))  #chr para int

#removendo placar completo
df <- subset(df, select = -c(Result))
```

-   criando uma nova coluna com Vitoria, Derrota ou Empate

``` r
#criando uma coluna com a vitoria, derrota ou empate

df$Result <- ifelse((df$Home > df$Away & df$Venue == "H") | (df$Home < df$Away & df$Venue == "A"), "Win", 
                    ifelse((df$Home < df$Away & df$Venue == "H") | (df$Home > df$Away & df$Venue == "A"), "Loss", 
                           "Tie"))
```

-   tratamento de exceção no Type

``` r
#acrescentar o type NULL -> MANO DE DIOS
df$Type[df$Type == ""] <- "MANO DE D10S"
```

-   tratamento de Minutes

``` r
#criando nova coluna com os acrescimos
df$Injury_Time <- as.integer(ifelse(grepl("\\+", df$Minute), sub(".*\\+(\\d+)", "\\1", df$Minute), NA))   
# Substituir os valores após o "+" por uma string vazia na coluna "Minute"
df$Minute <- sub("\\+\\d+", "", df$Minute) 


df$Minute <- as.numeric(as.character(df$Minute))  #chr para int
```

-   tratamento de Goal_assist

``` r
df$Goal_assist <- sub("", "No Assist", df$Goal_assist) #tirando os valores em branco do campo de Assistencia
df$Goal_assist <- sub("^No Assist(.+)$", "\\1", df$Goal_assist) #arrumando a cagada e tirando excesso de No assist
```

## Including Plots

Plots que serão gerados:

> gols x oponente
>
> gols x tipo de gol
>
> gols em vitoria, empate e derrota
>
> gols X temporada
>
> gols em cada dia do ano/mes
>
> gols em cada minuto
>
> gols X competicao
>
> jogadores que mais assistiram
>
> gols fora de casa
>
> gols em liga
>
> gols em mata mata (last 16, ..)

### Plotando alguns gráficos

```{R PieChart}
  library(ggplot2)
ggplot(df, aes(x = "", fill = Type)) +
  geom_bar(width = 1, color = "black") +
  coord_polar("y", start = 0) +
  labs(fill = "Tipo de Gol") +
  theme_void()  # Remove elementos de tema padrão (como grade e eixos)
```
